[package]
name = "crystallize-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
clap.workspace = true
bcrypt.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
flexi_logger.workspace = true
