[package]
name = "crystallize-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "crystallize-cli"
path = "src/main.rs"

[dependencies]
clap.workspace = true
crystallize-core.workspace = true
human-panic.workspace = true
