[package]
name = "crystallize-gui"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "crystallize"
path = "src/main.rs"

[dependencies]
crystallize-core.workspace = true
